# Generated by Django 3.1.2 on 2020-10-06 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='browser',
        ),
        migrations.RemoveField(
            model_name='client',
            name='device',
        ),
        migrations.RemoveField(
            model_name='client',
            name='link',
        ),
        migrations.RemoveField(
            model_name='client',
            name='os',
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='os',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Browser',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='OS',
        ),
    ]
